---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - update
- apiGroups:
  - autolock.takuteh.uk
  resources:
  - autolocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autolock.takuteh.uk
  resources:
  - autolocks/finalizers
  verbs:
  - update
- apiGroups:
  - autolock.takuteh.uk
  resources:
  - autolocks/status
  verbs:
  - get
  - patch
  - update
