//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDBSpec) DeepCopyInto(out *AuthDBSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDBSpec.
func (in *AuthDBSpec) DeepCopy() *AuthDBSpec {
	if in == nil {
		return nil
	}
	out := new(AuthDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Autolock) DeepCopyInto(out *Autolock) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Autolock.
func (in *Autolock) DeepCopy() *Autolock {
	if in == nil {
		return nil
	}
	out := new(Autolock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Autolock) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutolockList) DeepCopyInto(out *AutolockList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Autolock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutolockList.
func (in *AutolockList) DeepCopy() *AutolockList {
	if in == nil {
		return nil
	}
	out := new(AutolockList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutolockList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutolockSpec) DeepCopyInto(out *AutolockSpec) {
	*out = *in
	out.Webapp = in.Webapp
	out.Main = in.Main
	out.MQTT = in.MQTT
	out.AuthDB = in.AuthDB
	out.Webhook = in.Webhook
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutolockSpec.
func (in *AutolockSpec) DeepCopy() *AutolockSpec {
	if in == nil {
		return nil
	}
	out := new(AutolockSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutolockStatus) DeepCopyInto(out *AutolockStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutolockStatus.
func (in *AutolockStatus) DeepCopy() *AutolockStatus {
	if in == nil {
		return nil
	}
	out := new(AutolockStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.MainConfig = in.MainConfig
	out.MQTTConfig = in.MQTTConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTConfig) DeepCopyInto(out *MQTTConfig) {
	*out = *in
	out.Publish = in.Publish
	out.Subscribe = in.Subscribe
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTConfig.
func (in *MQTTConfig) DeepCopy() *MQTTConfig {
	if in == nil {
		return nil
	}
	out := new(MQTTConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTMessage) DeepCopyInto(out *MQTTMessage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTMessage.
func (in *MQTTMessage) DeepCopy() *MQTTMessage {
	if in == nil {
		return nil
	}
	out := new(MQTTMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTPublish) DeepCopyInto(out *MQTTPublish) {
	*out = *in
	out.Boot = in.Boot
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTPublish.
func (in *MQTTPublish) DeepCopy() *MQTTPublish {
	if in == nil {
		return nil
	}
	out := new(MQTTPublish)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSpec) DeepCopyInto(out *MQTTSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSpec.
func (in *MQTTSpec) DeepCopy() *MQTTSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSubscribe) DeepCopyInto(out *MQTTSubscribe) {
	*out = *in
	out.ChangeConfig = in.ChangeConfig
	out.Close = in.Close
	out.Open = in.Open
	out.RelayOff = in.RelayOff
	out.RelayOn = in.RelayOn
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSubscribe.
func (in *MQTTSubscribe) DeepCopy() *MQTTSubscribe {
	if in == nil {
		return nil
	}
	out := new(MQTTSubscribe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTTopicMessage) DeepCopyInto(out *MQTTTopicMessage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTTopicMessage.
func (in *MQTTTopicMessage) DeepCopy() *MQTTTopicMessage {
	if in == nil {
		return nil
	}
	out := new(MQTTTopicMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MainConfig) DeepCopyInto(out *MainConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MainConfig.
func (in *MainConfig) DeepCopy() *MainConfig {
	if in == nil {
		return nil
	}
	out := new(MainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MainSpec) DeepCopyInto(out *MainSpec) {
	*out = *in
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MainSpec.
func (in *MainSpec) DeepCopy() *MainSpec {
	if in == nil {
		return nil
	}
	out := new(MainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebappSpec) DeepCopyInto(out *WebappSpec) {
	*out = *in
	out.Ingress = in.Ingress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebappSpec.
func (in *WebappSpec) DeepCopy() *WebappSpec {
	if in == nil {
		return nil
	}
	out := new(WebappSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSpec) DeepCopyInto(out *WebhookSpec) {
	*out = *in
	out.Ingress = in.Ingress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSpec.
func (in *WebhookSpec) DeepCopy() *WebhookSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookSpec)
	in.DeepCopyInto(out)
	return out
}
